# Generated by Django 4.2 on 2026-02-24 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(db_index=True)),
                ('flag_type', models.CharField(choices=[('frequent_returns', 'Too Many Returns in 30 Days'), ('high_value', 'High Value Return'), ('quick_return', 'Return Within 1 Hour of Delivery'), ('address_pattern', 'Suspicious Address Pattern'), ('category_abuse', 'Repeated Returns in Same Category')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open - Needs Review'), ('investigating', 'Under Investigation'), ('cleared', 'Cleared - No Fraud'), ('confirmed', 'Fraud Confirmed')], default='open', max_length=20)),
                ('description', models.TextField()),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fraud_flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('customer_id', models.IntegerField(db_index=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('product_name', models.CharField(max_length=500)),
                ('product_sku', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home & Kitchen'), ('books', 'Books'), ('grocery', 'Grocery'), ('beauty', 'Beauty')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('ordered_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('shipping_address', models.TextField()),
                ('shipping_pincode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('customer_id', models.IntegerField(db_index=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('defective', 'Product is Defective/Damaged'), ('wrong_item', 'Wrong Item Delivered'), ('not_as_described', 'Product Not as Described'), ('size_issue', 'Size/Fit Issue'), ('quality_issue', 'Quality Not as Expected'), ('changed_mind', 'Changed My Mind'), ('late_delivery', 'Delivered Too Late'), ('missing_parts', 'Missing Parts/Accessories'), ('other', 'Other')], max_length=50)),
                ('reason_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Picked Up'), ('warehouse_received', 'Received at Warehouse'), ('quality_check', 'Quality Check in Progress'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('cancelled', 'Cancelled by Customer'), ('closed', 'Closed')], default='pending', max_length=30)),
                ('refund_method', models.CharField(choices=[('original', 'Original Payment Method'), ('wallet', 'Store Wallet/Credit'), ('bank_transfer', 'Bank Transfer')], default='original', max_length=20)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_reference', models.CharField(blank=True, max_length=200)),
                ('pickup_address', models.TextField(blank=True)),
                ('pickup_pincode', models.CharField(blank=True, max_length=10)),
                ('pickup_scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('pickup_completed_date', models.DateTimeField(blank=True, null=True)),
                ('logistics_partner', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_high_value', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='returns.order')),
            ],
            options={
                'db_table': 'return_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('changed_by', models.CharField(default='system', max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='returns.returnrequest')),
            ],
            options={
                'db_table': 'return_status_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_key', models.CharField(max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('content_type', models.CharField(default='image/jpeg', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='returns.returnrequest')),
            ],
            options={
                'db_table': 'return_images',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_id', 'status'], name='orders_custome_58f6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'),
        ),
        migrations.AddField(
            model_name='fraudflag',
            name='return_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='returns.returnrequest'),
        ),
        migrations.AddIndex(
            model_name='returnstatushistory',
            index=models.Index(fields=['return_request', 'created_at'], name='return_stat_return__fe6cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['customer_id', 'status'], name='return_requ_custome_ccdfb6_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['return_number'], name='return_requ_return__517635_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status', 'created_at'], name='return_requ_status_eae97b_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['is_flagged'], name='return_requ_is_flag_1cbaee_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudflag',
            index=models.Index(fields=['customer_id', 'flag_type'], name='fraud_flags_custome_33eca1_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudflag',
            index=models.Index(fields=['status'], name='fraud_flags_status_b47cca_idx'),
        ),
    ]
